server:
 http_listen_port: 9080
 grpc_listen_port: 0
clients:
 - url: http://localhost:3100/loki/api/v1/push
positions:
 filename: /var/lib/promtail/positions.yaml
scrape_configs:
 - job_name: suricata
 static_configs:
  - targets: [localhost]
    labels:
      job: suricata
      __path__: /var/log/suricata/eve.json